In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split

%load_ext autoreload
%autoreload 2

# making all pandas columns visable with display command
pd.set_option('display.max_columns', 500)

In [2]:
# df_EPL = pd.read_csv('datasets/EPL.csv', index_col = 0)
df_EPL = pd.read_csv('datasets/EPL_sort.csv', index_col = 0)
df_EPL = df_EPL.reset_index()
df_EPL

,index,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_y_card,home_r_card,away_y_card,away_r_card,home_foulcommit,away_foulcommit,home_shoton,away_shoton,home_shotoff,away_shotoff,home_cross,away_cross,home_corner,away_corner,home_possession,away_possession,HTP,ATP,Result
0,2,1731,2008/2009,1,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,0,0,2,0,13,12,4,11,3,5,15,19,1,8,46,54,0,0,H
1,6,1735,2008/2009,1,2008-08-16 00:00:00,489048,8549,8586,2,1,3.20,3.40,2.25,1,0,2,0,11,11,7,2,5,5,25,27,7,9,53,47,0,0,H
2,7,1736,2008/2009,1,2008-08-16 00:00:00,489049,8559,10194,3,1,1.83,3.50,4.50,1,0,2,0,14,15,5,1,7,6,22,29,4,3,47,53,0,0,A
3,3,1732,2008/2009,1,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,2,0,1,0,14,13,5,7,7,15,15,27,6,10,52,48,0,0,H
4,8,1737,2008/2009,1,2008-08-16 00:00:00,489050,8667,9879,2,1,2.60,3.20,2.80,3,0,0,0,10,9,5,4,5,6,16,14,5,6,53,47,0,0,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,2970,4699,2015/2016,38,2016-05-15 00:00:00,1987597,9825,10252,4,0,1.17,9.00,17.00,0,0,1,0,10,6,7,4,8,0,16,6,5,4,60,40,48,62,H
3036,2977,4706,2015/2016,38,2016-05-15 00:00:00,1987604,10003,8456,1,1,6.00,4.75,1.53,1,0,3,0,5,19,1,5,2,12,14,15,4,4,50,50,46,65,D
3037,2976,4705,2015/2016,38,2016-05-15 00:00:00,1987603,10194,8654,2,1,3.50,3.60,2.15,3,0,1,0,8,12,3,10,2,7,13,18,4,10,45,55,44,38,D
3038,2974,4703,2015/2016,38,2016-05-15 00:00:00,1987601,10261,8586,5,1,4.50,4.00,1.80,1,1,2,0,7,6,11,8,4,8,12,14,3,8,39,61,42,59,D
3039,2973,4702,2015/2016,38,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,1,0,0,0,9,8,5,5,4,2,16,5,7,1,68,32,63,42,H

In [3]:
df_EPL.sort_values('date',ascending=False)

,index,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_y_card,home_r_card,away_y_card,away_r_card,home_foulcommit,away_foulcommit,home_shoton,away_shoton,home_shotoff,away_shotoff,home_cross,away_cross,home_corner,away_corner,home_possession,away_possession,HTP,ATP,Result
3039,2973,4702,2015/2016,38,2016-05-17 00:00:00,1987600,10260,8678,3,1,1.67,4.20,5.25,1,0,0,0,9,8,5,5,4,2,16,5,7,1,68,32,63,42,H
3034,2978,4707,2015/2016,38,2016-05-15 00:00:00,1987605,9817,8472,2,2,2.05,3.75,3.70,1,0,0,0,10,9,6,2,10,2,9,12,7,4,49,51,60,42,H
3031,2975,4704,2015/2016,38,2016-05-15 00:00:00,1987602,8466,9826,4,1,1.36,5.50,9.00,1,0,2,0,6,14,4,5,13,3,20,15,2,5,49,51,49,80,D
3032,2979,4708,2015/2016,38,2016-05-15 00:00:00,1987606,8659,8650,1,1,2.40,3.60,3.00,3,0,1,0,12,13,5,3,8,3,12,14,7,5,33,67,44,34,H
3033,2972,4701,2015/2016,38,2016-05-15 00:00:00,1987599,8668,9850,3,0,1.80,4.00,4.50,0,0,0,0,6,10,9,4,4,5,17,17,4,11,47,53,34,70,H
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3,3,1732,2008/2009,1,2008-08-16 00:00:00,489045,8654,8528,2,1,1.91,3.40,4.20,2,0,1,0,14,13,5,7,7,15,15,27,6,10,52,48,0,0,H
1,6,1735,2008/2009,1,2008-08-16 00:00:00,489048,8549,8586,2,1,3.20,3.40,2.25,1,0,2,0,11,11,7,2,5,5,25,27,7,9,53,47,0,0,H
5,5,1734,2008/2009,1,2008-08-16 00:00:00,489047,8668,8655,2,3,2.00,3.30,4.00,2,0,2,0,11,11,2,8,7,8,14,21,3,4,51,49,0,0,A
6,1,1730,2008/2009,1,2008-08-16 00:00:00,489043,9825,8659,1,0,1.20,6.50,15.00,0,0,0,0,11,9,12,2,13,3,21,7,7,5,66,34,0,0,H
0,2,1731,2008/2009,1,2008-08-16 00:00:00,489044,8472,8650,0,1,5.50,3.60,1.67,0,0,2,0,13,12,4,11,3,5,15,19,1,8,46,54,0,0,H

In [12]:
#current_match_id = 1987598
#current_match = df_EPL[df_EPL['match_api_id'] == current_match_id]
current_match = df_EPL.loc[3032]
current_match

index                              2979
id                                 4708
season                        2015/2016
stage                                38
date                2016-05-15 00:00:00
match_api_id                    1987606
home_team_api_id                   8659
away_team_api_id                   8650
home_team_goal                        1
away_team_goal                        1
B365H                               2.4
B365D                               3.6
B365A                                 3
home_y_card                           3
home_r_card                           0
away_y_card                           1
away_r_card                           0
home_foulcommit                      12
away_foulcommit                      13
home_shoton                           5
away_shoton                           3
home_shotoff                          8
away_shotoff                          3
home_cross                           12
away_cross                           14
home_corner                           7
away_corner                           5
home_possession                      33
away_possession                      67
HTP                                  44
ATP                                  34
Result                                H
Name: 3032, dtype: object

In [13]:
team_away = current_match['home_team_api_id']
cm_date = current_match['date']
print(team_away)
print(cm_date)
# 10 chelsea's game before the match
def get_n_last_game(n, team_name, curr_date):
    n = 10
    df = df_EPL
    df = df[df['date'] < curr_date]
    df_away = df[df['away_team_api_id'] == team_name]
    df_home = df[df['home_team_api_id'] == team_name]
    df = pd.concat([df_away,df_home])
    return df.sort_values('date',ascending = False)[:n]

get_n_last_game(10,team_away,cm_date)

8659
2016-05-15 00:00:00

,index,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_y_card,home_r_card,away_y_card,away_r_card,home_foulcommit,away_foulcommit,home_shoton,away_shoton,home_shotoff,away_shotoff,home_cross,away_cross,home_corner,away_corner,home_possession,away_possession,HTP,ATP,Result
3019,2961,4690,2015/2016,37,2016-05-07 00:00:00,1989071,8678,8659,1,1,1.95,3.6,4.2,2,0,1,0,5,8,6,4,4,5,16,9,5,3,59,41,76,44,H
3006,2959,4688,2015/2016,36,2016-04-30 00:00:00,1989069,8659,8654,0,3,4.00,3.4,2.1,0,0,0,0,14,7,7,1,7,3,12,10,8,6,46,54,63,31,H
3005,2948,4677,2015/2016,35,2016-04-25 00:00:00,1989058,8586,8659,1,1,1.22,7.0,15.0,0,0,1,0,8,13,7,6,12,8,17,20,9,7,66,34,68,40,D
2998,2890,4619,2015/2016,30,2016-04-21 00:00:00,1989000,9825,8659,2,0,1.29,6.0,13.0,0,0,1,0,14,14,7,2,8,6,16,17,2,6,71,29,60,40,H
2985,2939,4668,2015/2016,34,2016-04-16 00:00:00,1989049,8659,9817,0,1,2.40,3.2,3.4,0,0,3,0,10,17,6,5,8,4,25,5,9,3,63,37,40,47,D
2973,2923,4652,2015/2016,33,2016-04-09 00:00:00,1989033,8456,8659,2,1,1.33,5.0,9.0,0,0,1,0,10,7,5,3,6,5,10,25,8,8,61,39,16,38,A
2963,2918,4647,2015/2016,32,2016-04-02 00:00:00,1989028,8472,8659,0,0,2.10,3.3,4.0,1,0,1,0,11,13,9,1,8,1,13,10,9,3,56,44,55,37,H
2954,2909,4638,2015/2016,31,2016-03-19 00:00:00,1989019,8659,9850,0,1,2.25,3.3,3.6,1,0,2,0,9,15,4,3,4,4,11,15,4,3,51,49,33,60,A
2946,2879,4608,2015/2016,29,2016-03-06 00:00:00,1988999,8659,10260,1,0,4.33,3.4,2.0,1,0,2,0,8,8,7,5,6,3,17,15,4,5,47,53,33,44,A
2928,2863,4592,2015/2016,28,2016-03-01 00:00:00,1988983,8197,8659,2,2,1.73,3.8,5.5,0,0,2,0,10,9,11,0,9,5,36,11,11,3,64,36,16,35,A

In [14]:
# get n last game both team (chelsea and lC)
def get_last_n_matches(current_match, n):
    team_away = current_match['home_team_api_id']
    team_home = current_match['away_team_api_id']
    cm_date = current_match['date']
    df_away = get_n_last_game(n,team_away,cm_date)
    df_home = get_n_last_game(n,team_home,cm_date)
    df_ = pd.concat([df_home,df_away])
    df_ = df_.sort_values(['date'])
    return df_

get_last_n_matches(current_match, 10)

,index,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_y_card,home_r_card,away_y_card,away_r_card,home_foulcommit,away_foulcommit,home_shoton,away_shoton,home_shotoff,away_shotoff,home_cross,away_cross,home_corner,away_corner,home_possession,away_possession,HTP,ATP,Result
2928,2863,4592,2015/2016,28,2016-03-01 00:00:00,1988983,8197,8659,2,2,1.73,3.8,5.50,0,0,2,0,10,9,11,0,9,5,36,11,11,3,64,36,16,35,A
2946,2879,4608,2015/2016,29,2016-03-06 00:00:00,1988999,8659,10260,1,0,4.33,3.4,2.00,1,0,2,0,8,8,7,5,6,3,17,15,4,5,47,53,33,44,A
2947,2871,4600,2015/2016,29,2016-03-06 00:00:00,1988991,9826,8650,1,2,3.80,3.5,2.10,1,0,4,0,12,17,8,8,4,5,20,14,6,6,39,61,36,47,H
2954,2909,4638,2015/2016,31,2016-03-19 00:00:00,1989019,8659,9850,0,1,2.25,3.3,3.60,1,0,2,0,9,15,4,3,4,4,11,15,4,3,51,49,33,60,A
2960,2905,4634,2015/2016,31,2016-03-20 00:00:00,1989015,8466,8650,3,2,2.63,3.4,2.88,1,0,3,0,10,13,4,12,10,3,18,10,3,5,50,50,25,26,D
2964,2914,4643,2015/2016,32,2016-04-02 00:00:00,1989024,8650,8586,1,1,2.50,3.4,3.00,2,0,0,0,11,11,10,7,3,8,14,15,12,9,43,57,16,41,A
2963,2918,4647,2015/2016,32,2016-04-02 00:00:00,1989028,8472,8659,0,0,2.10,3.3,4.00,1,0,1,0,11,13,9,1,8,1,13,10,9,3,56,44,55,37,H
2973,2923,4652,2015/2016,33,2016-04-09 00:00:00,1989033,8456,8659,2,1,1.33,5.0,9.00,0,0,1,0,10,7,5,3,6,5,10,25,8,8,61,39,16,38,A
2982,2922,4651,2015/2016,33,2016-04-10 00:00:00,1989032,8650,10194,4,1,1.55,4.0,5.75,0,0,2,0,16,16,5,2,6,8,16,18,6,3,53,47,62,53,H
2985,2939,4668,2015/2016,34,2016-04-16 00:00:00,1989049,8659,9817,0,1,2.40,3.2,3.40,0,0,3,0,10,17,6,5,8,4,25,5,9,3,63,37,40,47,D
2991,2931,4660,2015/2016,34,2016-04-17 00:00:00,1989041,8678,8650,1,2,3.60,3.5,2.15,0,0,0,0,9,9,11,9,4,9,19,10,5,4,51,49,41,54,A
2995,2851,4580,2015/2016,27,2016-04-20 00:00:00,1988971,8650,8668,4,0,1.73,4.0,5.00,1,0,1,1,9,12,21,1,12,2,25,3,9,1,67,33,54,41,H
2998,2890,4619,2015/2016,30,2016-04-21 00:00:00,1989000,9825,8659,2,0,1.29,6.0,13.00,0,0,1,0,14,14,7,2,8,6,16,17,2,6,71,29,60,40,H
3000,2944,4673,2015/2016,35,2016-04-23 00:00:00,1989054,8650,10261,2,2,1.57,4.5,6.00,1,0,1,0,8,17,7,1,3,3,24,14,5,4,67,33,41,47,A
3005,2948,4677,2015/2016,35,2016-04-25 00:00:00,1989058,8586,8659,1,1,1.22,7.0,15.00,0,0,1,0,8,13,7,6,12,8,17,20,9,7,66,34,68,40,D
3006,2959,4688,2015/2016,36,2016-04-30 00:00:00,1989069,8659,8654,0,3,4.00,3.4,2.10,0,0,0,0,14,7,7,1,7,3,12,10,8,6,46,54,63,31,H
3013,2957,4686,2015/2016,36,2016-05-01 00:00:00,1989067,10003,8650,3,1,3.10,3.5,2.40,2,0,4,0,12,13,9,5,6,5,12,8,4,7,47,53,54,64,H
3019,2961,4690,2015/2016,37,2016-05-07 00:00:00,1989071,8678,8659,1,1,1.95,3.6,4.20,2,0,1,0,5,8,6,4,4,5,16,9,5,3,59,41,76,44,H
3025,2964,4693,2015/2016,37,2016-05-08 00:00:00,1989074,8650,9817,2,0,1.50,4.5,7.50,1,0,2,0,10,15,9,3,7,10,17,20,8,8,66,34,70,57,A
3028,2894,4623,2015/2016,30,2016-05-11 00:00:00,1989004,8650,8455,1,1,2.00,3.8,3.80,3,0,1,0,11,12,17,9,10,3,10,6,7,3,55,45,31,44,H

In [15]:
get_last_n_matches(current_match, 10).shape

(20, 32)

In [23]:
#create X and y
X = np.zeros((df_EPL.shape[0], 20, 32))
drop_ids = []
for i in range(df_EPL.shape[0]):
    current_match = df_EPL.loc[i]
        #print(current_match)
    
    tmp = get_last_n_matches(current_match, 10)
    
    #one hot encode result
    tmp_2 = pd.get_dummies(tmp['Result'], prefix= 'Result')
    tmp = pd.concat([tmp, tmp_2], axis=1)
    tmp = tmp.drop(columns= ['season','date','Result'])
    
    #if shape not 20 then not enough history, it will delete later
    
    if tmp.shape == (20,32):
        X[i] = tmp
    else:
        drop_ids.append(i)
        
        
y_cat = pd.Categorical(df_EPL['Result'])
y = y_cat.codes
# X = X[counter:]
print(X.shape)
#print(df_EPL.shape)

(3040, 20, 32)

In [24]:
#print(X,y)
X = np.delete(X, drop_ids,axis=0)
y = np.delete(y, drop_ids,axis=0)

(2792,)

In [25]:
print(X.shape)
print(y.shape)

(2792, 20, 32)
(2792,)

In [26]:
np.save("X_2d",X)
np.save("y_2d",y)