## Dataset Preparation
Download __database.sqlite__ from [here](https://www.kaggle.com/hugomathien/soccer)

In [66]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load in 

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import sqlite3
import matplotlib.pyplot as plt
import xml.etree.ElementTree as ET

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list the files in the input directory

path = "datasets/"  #Insert path here
database = path + 'database.sqlite'

# Input data files are available in the "../input/" directory.
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

# import os
# for dirname, _, filenames in os.walk('/kaggle/input'):
#     for filename in filenames:
#         print(os.path.join(dirname, filename))

# Any results you write to the current directory are saved as output\

In [67]:
conn = sqlite3.connect(database)

tables = pd.read_sql("""SELECT *
                        FROM sqlite_master
                        WHERE type='table';""", conn)
type(tables)

pandas.core.frame.DataFrame

In [68]:
tables

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,4,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Player_Attributes,Player_Attributes,11,"CREATE TABLE ""Player_Attributes"" (\n\t`id`\tIN..."
2,table,Player,Player,14,CREATE TABLE `Player` (\n\t`id`\tINTEGER PRIMA...
3,table,Match,Match,18,CREATE TABLE `Match` (\n\t`id`\tINTEGER PRIMAR...
4,table,League,League,24,CREATE TABLE `League` (\n\t`id`\tINTEGER PRIMA...
5,table,Country,Country,26,CREATE TABLE `Country` (\n\t`id`\tINTEGER PRIM...
6,table,Team,Team,29,"CREATE TABLE ""Team"" (\n\t`id`\tINTEGER PRIMARY..."
7,table,Team_Attributes,Team_Attributes,2,CREATE TABLE `Team_Attributes` (\n\t`id`\tINTE...

In [69]:
team_t = pd.read_sql("""SELECT * FROM Team""", conn)

In [70]:
team_t

        id  team_api_id  team_fifa_api_id      team_long_name team_short_name
0        1         9987             673.0            KRC Genk             GEN
1        2         9993             675.0        Beerschot AC             BAC
2        3        10000           15005.0    SV Zulte-Waregem             ZUL
3        4         9994            2007.0    Sporting Lokeren             LOK
4        5         9984            1750.0   KSV Cercle Brugge             CEB
..     ...          ...               ...                 ...             ...
294  49479        10190             898.0       FC St. Gallen             GAL
295  49837        10191            1715.0             FC Thun             THU
296  50201         9777             324.0         Servette FC             SER
297  50204         7730            1862.0  FC Lausanne-Sports             LAU
298  51606         7896               NaN              Lugano             LUG

[299 rows x 5 columns]

In [71]:
match_t = pd.read_sql("""SELECT * FROM Match""", conn)
match_t

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,9987,9993,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,10000,9994,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,9984,8635,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,9991,9998,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,7947,9985,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,10190,10191,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,42231.0,678384.0,95220.0,638592.0,413155.0,45780.0,171229.0,67333.0,119839.0,143790.0,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,9824,10199,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,33272.0,41621.0,25813.0,257845.0,114735.0,42237.0,113227.0,358156.0,32343.0,531309.0,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,9956,10179,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,157856.0,274779.0,177689.0,294256.0,42258.0,39979.0,173936.0,147959.0,451983.0,80564.0,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,7896,10243,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,NaN,8881.0,173534.0,39646.0,282287.0,340790.0,393337.0,8893.0,614454.0,93229.0,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,10192,9931,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,274787.0,492132.0,108451.0,25815.0,94553.0,384376.0,598355.0,36785.0,45174.0,302079.0,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [72]:
m = team_t.set_index('team_api_id')['team_long_name'].to_dict()
h = match_t.filter(like='home_team_api_id')
match_t[h.columns] = h.replace(m)
a = match_t.filter(like='away_team_api_id')
match_t[a.columns] = a.replace(m)

In [73]:
match_t

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1,1,1,2008/2009,1,2008-08-17 00:00:00,492473,KRC Genk,Beerschot AC,1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.73,3.40,5.00,1.75,3.35,4.20,1.85,3.2,3.5,1.80,3.3,3.75,NaN,NaN,NaN,1.70,3.30,4.33,1.90,3.3,4.00,1.65,3.40,4.50,1.78,3.25,4.00,1.73,3.40,4.20
1,2,1,1,2008/2009,1,2008-08-16 00:00:00,492474,SV Zulte-Waregem,Sporting Lokeren,0,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.95,3.20,3.60,1.80,3.30,3.95,1.90,3.2,3.5,1.90,3.2,3.50,NaN,NaN,NaN,1.83,3.30,3.60,1.95,3.3,3.80,2.00,3.25,3.25,1.85,3.25,3.75,1.91,3.25,3.60
2,3,1,1,2008/2009,1,2008-08-16 00:00:00,492475,KSV Cercle Brugge,RSC Anderlecht,0,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,2.38,3.30,2.75,2.40,3.30,2.55,2.60,3.1,2.3,2.50,3.2,2.50,NaN,NaN,NaN,2.50,3.25,2.40,2.63,3.3,2.50,2.35,3.25,2.65,2.50,3.20,2.50,2.30,3.20,2.75
3,4,1,1,2008/2009,1,2008-08-17 00:00:00,492476,KAA Gent,RAEC Mons,5,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,1.44,3.75,7.50,1.40,4.00,6.80,1.40,3.9,6.0,1.44,3.6,6.50,NaN,NaN,NaN,1.44,3.75,6.00,1.44,4.0,7.50,1.45,3.75,6.50,1.50,3.75,5.50,1.44,3.75,6.50
4,5,1,1,2008/2009,1,2008-08-16 00:00:00,492477,FCV Dender EH,Standard de Liège,1,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,None,None,None,None,None,None,None,None,5.00,3.50,1.65,5.00,3.50,1.60,4.00,3.3,1.7,4.00,3.4,1.72,NaN,NaN,NaN,4.20,3.40,1.70,4.50,3.5,1.73,4.50,3.40,1.65,4.50,3.50,1.65,4.75,3.30,1.67
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25974,25975,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992091,FC St. Gallen,FC Thun,1,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,42231.0,678384.0,95220.0,638592.0,413155.0,45780.0,171229.0,67333.0,119839.0,143790.0,195215.0,462944.0,563066.0,8800.0,67304.0,158253.0,133126.0,186524.0,93223.0,121115.0,232110.0,289732.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25975,25976,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992092,FC Vaduz,FC Luzern,1,2,1.0,3.0,5.0,7.0,2.0,4.0,6.0,8.0,5.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,3.0,5.0,7.0,3.0,5.0,7.0,1.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,9.0,11.0,11.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,33272.0,41621.0,25813.0,257845.0,114735.0,42237.0,113227.0,358156.0,32343.0,531309.0,37257.0,42276.0,114792.0,150007.0,178119.0,27232.0,570830.0,260708.0,201704.0,36382.0,34082.0,95257.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25976,25977,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992093,Grasshopper Club Zürich,FC Sion,2,0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,157856.0,274779.0,177689.0,294256.0,42258.0,39979.0,173936.0,147959.0,451983.0,80564.0,289472.0,10637.0,67349.0,202663.0,32597.0,114794.0,188114.0,25840.0,482200.0,95230.0,451335.0,275122.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25977,25978,24558,24558,2015/2016,9,2015-09-22 00:00:00,1992094,Lugano,FC Zürich,0,0,1.0,2.0,4.0,6.0,8.0,3.0,7.0,5.0,3.0,5.0,7.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,10.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,NaN,8881.0,173534.0,39646.0,282287.0,340790.0,393337.0,8893.0,614454.0,93229.0,178142.0,274776.0,121080.0,197757.0,260964.0,231614.0,113235.0,41116.0,462608.0,42262.0,92252.0,194532.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25978,25979,24558,24558,2015/2016,9,2015-09-23 00:00:00,1992095,BSC Young Boys,FC Basel,4,3,1.0,2.0,4.0,6.0,8.0,2.0,4.0,6.0,8.0,4.0,6.0,1.0,2.0,4.0,6.0,8.0,4.0,6.0,3.0,5.0,7.0,5.0,1.0,3.0,3.0,3.0,3.0,7.0,7.0,7.0,7.0,10.0,10.0,1.0,3.0,3.0,3.0,3.0,6.0,6.0,8.0,8.0,8.0,11.0,274787.0,492132.0,108451.0,25815.0,94553.0,384376.0,598355.0,36785.0,45174.0,302079.0,71764.0,156175.0,95216.0,172768.0,22834.0,458806.0,207234.0,25772.0,40274.0,34035.0,41726.0,527103.0,None,None,None,None,None,None,None,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [74]:
league_t = pd.read_sql("""SELECT * FROM League""", conn)
league_t

       id  country_id                      name
0       1           1    Belgium Jupiler League
1    1729        1729    England Premier League
2    4769        4769            France Ligue 1
3    7809        7809     Germany 1. Bundesliga
4   10257       10257             Italy Serie A
5   13274       13274    Netherlands Eredivisie
6   15722       15722        Poland Ekstraklasa
7   17642       17642  Portugal Liga ZON Sagres
8   19694       19694   Scotland Premier League
9   21518       21518           Spain LIGA BBVA
10  24558       24558  Switzerland Super League

In [75]:
selected_leagues = pd.read_sql("""SELECT *
                        FROM League
                        WHERE id IN(1729, 21518);""", conn)
selected_leagues

      id  country_id                    name
0   1729        1729  England Premier League
1  21518       21518         Spain LIGA BBVA

In [76]:
matches = pd.read_sql("""SELECT *
                        FROM Match
                        WHERE league_id IN(1729, 21518);""", conn)
matches

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,home_player_X1,home_player_X2,home_player_X3,home_player_X4,home_player_X5,home_player_X6,home_player_X7,home_player_X8,home_player_X9,home_player_X10,home_player_X11,away_player_X1,away_player_X2,away_player_X3,away_player_X4,away_player_X5,away_player_X6,away_player_X7,away_player_X8,away_player_X9,away_player_X10,away_player_X11,home_player_Y1,home_player_Y2,home_player_Y3,home_player_Y4,home_player_Y5,home_player_Y6,home_player_Y7,home_player_Y8,home_player_Y9,home_player_Y10,home_player_Y11,away_player_Y1,away_player_Y2,away_player_Y3,away_player_Y4,away_player_Y5,away_player_Y6,away_player_Y7,away_player_Y8,away_player_Y9,away_player_Y10,away_player_Y11,home_player_1,home_player_2,home_player_3,home_player_4,home_player_5,home_player_6,home_player_7,home_player_8,home_player_9,home_player_10,home_player_11,away_player_1,away_player_2,away_player_3,away_player_4,away_player_5,away_player_6,away_player_7,away_player_8,away_player_9,away_player_10,away_player_11,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A,BWH,BWD,BWA,IWH,IWD,IWA,LBH,LBD,LBA,PSH,PSD,PSA,WHH,WHD,WHA,SJH,SJD,SJA,VCH,VCD,VCA,GBH,GBD,GBA,BSH,BSD,BSA
0,1729,1729,1729,2008/2009,1,2008-08-17 00:00:00,489042,10260,10261,1,1,1,2,4,6,8,2,4,6,8,4,6,1,2,4,6,8,2,4,6,8,5,5.0,1,3,3,3,3,7,7,7,7,10,10,1,3,3,3,3,7,7,7,7,9,11.0,30726.0,30362.0,30620.0,30865.0,32569.0,24148.0,34944.0,30373.0,24154.0,24157.0,30829.0,24224.0,25518.0,24228.0,30929.0,29581.0,38807.0,40565.0,30360.0,33852.0,34574.0,37799.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>56</comment><event...,1.29,5.50,11.00,1.30,4.75,8.25,1.30,4.4,8.50,1.25,4.50,10.00,NaN,NaN,NaN,1.25,4.5,10.00,1.25,5.00,10.00,1.28,5.5,12.00,1.30,4.75,10.0,1.29,4.50,11.00
1,1730,1729,1729,2008/2009,1,2008-08-16 00:00:00,489043,9825,8659,1,0,1,2,4,6,8,2,4,6,8,4,6,1,2,4,6,8,5,7,9,1,3,5.0,1,3,3,3,3,7,7,7,7,10,10,1,3,3,3,3,7,7,7,7,7,11.0,23686.0,26111.0,38835.0,30986.0,31291.0,31013.0,30935.0,39297.0,26181.0,30960.0,36410.0,36373.0,36832.0,23115.0,37280.0,24728.0,24664.0,31088.0,23257.0,24171.0,25922.0,27267.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card />,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>65</comment><event...,1.20,6.50,15.00,1.22,5.50,10.00,1.20,5.2,11.00,1.20,5.00,11.00,NaN,NaN,NaN,1.17,5.5,12.00,1.20,5.50,12.00,1.25,6.0,13.00,1.22,5.50,13.0,1.22,5.00,13.00
2,1731,1729,1729,2008/2009,1,2008-08-16 00:00:00,489044,8472,8650,0,1,1,2,4,6,8,2,4,6,8,4,6,1,2,4,6,8,2,4,6,8,4,6.0,1,3,3,3,3,7,7,7,7,10,10,1,3,3,3,3,7,7,7,7,10,10.0,32562.0,38836.0,24446.0,24408.0,36786.0,38802.0,24655.0,17866.0,30352.0,23927.0,24410.0,30660.0,37442.0,30617.0,24134.0,414792.0,37139.0,30618.0,40701.0,24800.0,24635.0,30853.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>45</comment><event...,5.50,3.60,1.67,5.00,3.35,1.67,4.50,3.5,1.65,4.50,3.30,1.67,NaN,NaN,NaN,5.50,3.3,1.57,4.33,3.40,1.73,5.50,3.8,1.65,5.00,3.40,1.7,4.50,3.40,1.73
3,1732,1729,1729,2008/2009,1,2008-08-16 00:00:00,489045,8654,8528,2,1,1,2,4,6,8,2,4,6,8,4,6,1,2,6,8,4,2,4,6,8,4,6.0,1,3,3,3,3,7,7,7,7,10,10,1,3,3,3,3,7,7,7,7,10,10.0,36374.0,30966.0,23818.0,37277.0,30687.0,36394.0,37169.0,24223.0,24773.0,34543.0,23139.0,34421.0,34987.0,35472.0,111865.0,25005.0,35327.0,25150.0,97988.0,41877.0,127857.0,34466.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>50</comment><event...,1.91,3.40,4.20,1.90,3.20,3.80,1.80,3.3,3.80,1.80,3.20,4.00,NaN,NaN,NaN,1.83,3.2,3.75,1.91,3.25,3.75,1.90,3.5,4.35,1.91,3.25,4.0,1.91,3.25,3.80
4,1733,1729,1729,2008/2009,1,2008-08-17 00:00:00,489046,10252,8456,4,2,1,2,4,6,8,2,4,6,8,4,6,1,2,4,6,8,1,3,5,7,9,5.0,1,3,3,3,3,7,7,7,7,10,10,1,3,3,3,3,7,7,7,7,7,11.0,30380.0,30357.0,24658.0,43280.0,23282.0,38609.0,24780.0,23782.0,23354.0,23264.0,26165.0,31432.0,46403.0,24208.0,23939.0,33963.0,47413.0,40198.0,42119.0,NaN,33633.0,107216.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><corners>1</corners></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>51</comment><event...,1.91,3.40,4.33,1.95,3.20,3.60,2.00,3.2,3.30,1.83,3.20,3.75,NaN,NaN,NaN,1.91,3.2,3.50,1.91,3.25,3.75,1.90,3.5,4.35,1.91,3.25,4.0,1.91,3.30,3.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6075,24553,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030167,9906,10267,2,1,1,2,4,6,8,3,5,7,3,5,7,1,2,4,6,8,2,4,6,8,4,6.0,1,3,3,3,3,7,7,7,10,10,10,1,3,3,3,3,7,7,7,7,10,10.0,177126.0,38424.0,474589.0,56678.0,41167.0,33635.0,30871.0,184533.0,354467.0,51360.0,184138.0,489240.0,361757.0,184999.0,361710.0,391058.0,75307.0,40148.0,570432.0,361770.0,193869.0,428947.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>49</comment><stats...,1.57,3.80,6.50,1.57,4.00,6.50,1.65,3.7,4.90,1.57,3.75,6.50,1.58,4.05,7.06,1.62,3.3,7.00,NaN,NaN,NaN,1.57,4.0,7.00,NaN,NaN,NaN,NaN,NaN,NaN
6076,24554,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030168,9864,9783,2,0,1,2,4,6,8,4,6,3,5,7,5,1,2,4,6,8,2,4,6,8,4,6.0,1,3,3,3,3,6,6,8,8,8,11,1,3,3,3,3,7,7,7,7,10,10.0,25563.0,104382.0,477471.0,41707.0,38842.0,39198.0,238841.0,261599.0,37450.0,215927.0,213653.0,32678.0,103905.0,191906.0,121872.0,33848.0,279173.0,51953.0,40668.0,474680.0,37653.0,194660.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><event_incident_typefk>876</eve...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>53</comment><stats...,2.25,3.25,3.40,2.35,3.10,3.10,2.20,3.2,3.20,2.25,3.20,3.25,2.36,3.36,3.36,2.38,3.1,3.10,NaN,NaN,NaN,2.30,3.4,3.40,NaN,NaN,NaN,NaN,NaN,NaN
6077,24555,21518,21518,2015/2016,9,2015-10-26 00:00:00,2030169,8315,9869,3,0,1,2,4,6,8,4,5,6,3,7,5,1,2,4,6,8,3,5,7,7,3,5.0,1,3,3,3,3,6,8,6,8,8,11,1,3,3,3,3,7,7,7,10,10,10.0,33764.0,181297.0,159881.0,411617.0,154938.0,182224.0,33871.0,45749.0,604105.0,96619.0,33028.0,102394.0,150480.0,384374.0,150764.0,239965.0,359191.0,202639.0,242477.0,541557.0,395154.0,206301.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>49</comment><stats...,1.53,4.00,7.00,1.55,4.00,6.50,1.60,3.7,5.40,1.50,4.00,6.50,1.55,4.31,6.95,1.57,3.5,7.00,NaN,NaN,NaN,1.55,4.2,7.00,NaN,NaN,NaN,NaN,NaN,NaN
6078,24556,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030170,7878,8603,1,1,1,2,4,6,8,3,5,7,3,5,7,1,2,4,6,8,2,4,6,8,4,6.0,1,3,3,3,3,7,7,7,10,10,10,1,3,3,3,3,7,7,7,7,10,10.0,104986.0,261609.0,108572.0,2752.0,239350.0,2805.0,170667.0,80492.0,534484.0,161291.0,43372.0,40648.0,239964.0,268273.0,27461.0,445907.0,37824.0,111801.0,535600.0,193226.0,114746.0,96652.0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>50</comment><stats...,2.30,3.25,3.25,2.35,3.25,3.00,2.40,3.3,2.75,2.30,3.20,3.10,2.34,3.40,3.35,2.40,3.1,3.10,NaN,NaN,NaN,2.30,3.4,3.30,NaN,NaN,NaN,NaN,NaN,NaN
6079,24557,21518,21518,2015/2016,9,2015-10-23 00:00:00,2030171,8370,8558,3,0,1,2,4,6,8,4,6,3,5,7,5,1,2,4,6,8,4,6,3,5,7,5.0,1,3,3,3,3,6,6,8,8,8,11,1,3,3,3,3,6,6,8,8,8,11.0,37579.0,183449.0,34104.0,420568.0,40220.0,186121.0,75004.0,256727.0,427893.0,36130.0,46808.0,532942.0,213814.0,193930.0,257855.0,190452.0,107930.0,161651.0,88986.0,498033.0,52004.0,41622.0,<goal><value><comment>p</comment><stats><penal...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>59</comment><stats...,2.20,3.40,3.20,2.25,3.50,3.20,2.30,3.3,2.90,2.10,3.40,3.30,2.20,3.61,3.46,2.20,3.4,3.20,NaN,NaN,NaN,2.20,3.6,3.50,NaN,NaN,NaN,NaN,NaN,NaN

In [77]:
# Replace team_api_id with team_long_name
#m = team_t.set_index('team_api_id')['team_long_name'].to_dict()
#h = matches.filter(like='home_team_api_id')
#matches[h.columns] = h.replace(m)
#a = matches.filter(like='away_team_api_id')
#matches[a.columns] = a.replace(m)

In [78]:
df = matches[matches.columns.drop(list(matches.filter(regex='player|BW|IW|LB|PS|WH|SJ|VC|GB|BS')))]
df_EPL = df[df['league_id'] == 1729]
len(df_EPL)

3040

In [79]:
df_LaLiga = df[df['league_id'] == 21518]
df_LaLiga.reset_index(drop=True, inplace=True)
df_LaLiga

,id,country_id,league_id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,goal,shoton,shotoff,foulcommit,card,cross,corner,possession,B365H,B365D,B365A
0,21518,21518,21518,2008/2009,1,2008-08-30 00:00:00,530023,10267,8661,3,0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><corners>1</corners></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>53</comment><event...,1.70,3.60,5.25
1,21519,21518,21518,2008/2009,1,2008-08-31 00:00:00,530084,8371,10205,1,1,<goal><value><comment>n</comment><stats><goals...,<shoton />,<shotoff />,<foulcommit />,<card><value><comment>y</comment><stats><ycard...,<cross />,<corner />,<possession />,2.80,3.30,2.50
2,21520,21518,21518,2008/2009,1,2008-08-31 00:00:00,530085,9783,8633,2,1,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>44</comment><event...,3.50,3.30,2.10
3,21521,21518,21518,2008/2009,1,2008-08-31 00:00:00,530086,8388,8634,1,0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>27</comment><event...,7.00,4.00,1.50
4,21522,21518,21518,2008/2009,1,2008-08-31 00:00:00,530087,8696,8302,1,1,<goal><value><comment>n</comment><stats><goals...,<shoton />,<shotoff />,<foulcommit />,<card><value><comment>y</comment><stats><ycard...,<cross />,<corner />,<possession />,2.80,3.30,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3035,24553,21518,21518,2015/2016,9,2015-10-25 00:00:00,2030167,9906,10267,2,1,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>49</comment><stats...,1.57,3.80,6.50
3036,24554,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030168,9864,9783,2,0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><event_incident_typefk>876</eve...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>53</comment><stats...,2.25,3.25,3.40
3037,24555,21518,21518,2015/2016,9,2015-10-26 00:00:00,2030169,8315,9869,3,0,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>49</comment><stats...,1.53,4.00,7.00
3038,24556,21518,21518,2015/2016,9,2015-10-24 00:00:00,2030170,7878,8603,1,1,<goal><value><comment>n</comment><stats><goals...,<shoton><value><stats><shoton>1</shoton></stat...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>50</comment><stats...,2.30,3.25,3.25
3039,24557,21518,21518,2015/2016,9,2015-10-23 00:00:00,2030171,8370,8558,3,0,<goal><value><comment>p</comment><stats><penal...,<shoton><value><stats><blocked>1</blocked></st...,<shotoff><value><stats><shotoff>1</shotoff></s...,<foulcommit><value><stats><foulscommitted>1</f...,<card><value><comment>y</comment><stats><ycard...,<cross><value><stats><crosses>1</crosses></sta...,<corner><value><stats><corners>1</corners></st...,<possession><value><comment>59</comment><stats...,2.20,3.40,3.20

In [80]:
# count shotonm shotoff, foulcommut
# for i in range(len(df_EPL['shoton'])):
#     root = ET.fromstring(df_EPL['shoton'][i])
#     count = len(root.getchildren())
#     df_EPL.at[i,'shoton'] = count
# for i in range(len(df_EPL['shotoff'])):
#     root = ET.fromstring(df_EPL['shotoff'][i])
#     count = len(root.getchildren())
#     df_EPL.at[i,'shotoff'] = count
# for i in range(len(df_EPL['foulcommit'])):
#     root = ET.fromstring(df_EPL['foulcommit'][i])
#     count = len(root.getchildren())
#     df_EPL.at[i,'foulcommit'] = count

In [81]:
#add home cway yellow and red cards stat
# Unsportsmanlike Condduct data has no card_type, treat it as a yellow card 
# reference: https://en.wikipedia.org/wiki/Fouls_and_misconduct_(association_football)#Red_card_(dismissal)
# if no team record for card data, omit card row

#EPL
home_y_card =[]
away_y_card =[]
home_r_card =[]
away_r_card = []
NoneType = type(None)
for i in range(len(df_EPL['card'])):
    root = ET.fromstring(df_EPL['card'][i])
    home_y_card_count = 0
    away_y_card_count = 0
    home_r_card_count = 0
    away_r_card_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                if type(child.find('card_type')) != NoneType:
                    if "y" in child.find('card_type').text:
                        home_y_card_count +=1
                    else:
                        home_r_card_count +=1
                else:
                    home_y_card_count +=1
            else:
                if type(child.find('card_type')) != NoneType:
                    if "y" in child.find('card_type').text:
                        away_y_card_count +=1
                    else:
                        away_r_card_count +=1
                else:
                    away_y_card_count +=1
    home_y_card.append(home_y_card_count)
    home_r_card.append(home_r_card_count)
    away_y_card.append(away_y_card_count)
    away_r_card.append(away_r_card_count)

df_EPL.loc[:,"home_y_card"] = home_y_card
df_EPL.loc[:,"home_r_card"] = home_r_card
df_EPL.loc[:,"away_y_card"] = away_y_card
df_EPL.loc[:,"away_r_card"] = away_r_card

In [82]:
#LALIGA
home_y_card =[]
away_y_card =[]
home_r_card =[]
away_r_card = []
NoneType = type(None)
for i in range(len(df_LaLiga['card'])):
    print(i)
    root = ET.fromstring(df_LaLiga['card'][i])
    home_y_card_count = 0
    away_y_card_count = 0
    home_r_card_count = 0
    away_r_card_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_LaLiga['home_team_api_id'][i]):
                if type(child.find('card_type')) != NoneType:
                    if "y" in child.find('card_type').text:
                        home_y_card_count +=1
                    else:
                        home_r_card_count +=1
                else:
                    home_y_card_count +=1
            else:
                if type(child.find('card_type')) != NoneType:
                    if "y" in child.find('card_type').text:
                        away_y_card_count +=1
                    else:
                        away_r_card_count +=1
                else:
                    away_y_card_count +=1
    home_y_card.append(home_y_card_count)
    home_r_card.append(home_r_card_count)
    away_y_card.append(away_y_card_count)
    away_r_card.append(away_r_card_count)
    
df_LaLiga.loc[:,"home_y_card"] = home_y_card
df_LaLiga.loc[:,"home_r_card"] = home_r_card
df_LaLiga.loc[:,"away_y_card"] = away_y_card
df_LaLiga.loc[:,"away_r_card"] = away_r_card

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100
101
102
103
104
105
106
107
108
109
110
111
112
113
114
115
116
117
118
119
120
121
122
123
124
125
126
127
128
129
130
131
132
133
134
135
136
137
138
139
140
141
142
143
144
145
146
147
148
149
150
151
152
153
154
155
156
157
158
159
160
161
162
163
164
165
166
167
168
169
170
171
172
173
174
175
176
177
178
179
180
181
182
183
184
185
186
187
188
189
190
191
192
193
194
195
196
197
198
199
200
201
202
203
204
205
206
207
208
209
210
211
212
213
214
215
216
217
218
219
220
221
222
223
224
225
226
227
228
229
230
231
232
233
234
235
236
237
238
239
240
241
242
243
244
245
246
247
248
249
250
251
252
253
254
255
256
257
258
259
260
261
262
263
264
265
266
267
268
269
270
271
272
273
274
275
276
277
278
279
280
281
282
283
284
285
286
287
288
289
290
291
292
293
294
295
296
297
298
299
300
301
302
303
304
305
306
307
308
309
310
311
312
313
314
315
316
317
318
319
320
321
322
323
324
325
326
327
328
329
330
331
332
333
334
335
336
337
338
339
340
341
342
343
344
345
346
347
348
349
350
351
352
353
354
355
356
357
358
359
360
361
362
363
364
365
366
367
368
369
370
371
372
373
374
375
376
377
378
379
380
381
382
383
384
385
386
387
388
389
390
391
392
393
394
395
396
397
398
399
400
401
402
403
404
405
406
407
408
409
410
411
412
413
414
415
416
417
418
419
420
421
422
423
424
425
426
427
428
429
430
431
432
433
434
435
436
437
438
439
440
441
442
443
444
445
446
447
448
449
450
451
452
453
454
455
456
457
458
459
460
461
462
463
464
465
466
467
468
469
470
471
472
473
474
475
476
477
478
479
480
481
482
483
484
485
486
487
488
489
490
491
492
493
494
495
496
497
498
499
500
501
502
503
504
505
506
507
508
509
510
511
512
513
514
515
516
517
518
519
520
521
522
523
524
525
526
527
528
529
530
531
532
533
534
535
536
537
538
539
540
541
542
543
544
545
546
547
548
549
550
551
552
553
554
555
556
557
558
559
560
561
562
563
564
565
566
567
568
569
570
571
572
573
574
575
576
577
578
579
580
581
582
583
584
585
586
587
588
589
590
591
592
593
594
595
596
597
598
599
600
601
602
603
604
605
606
607
608
609
610
611
612
613
614
615
616
617
618
619
620
621
622
623
624
625
626
627
628
629
630
631
632
633
634
635
636
637
638
639
640
641
642
643
644
645
646
647
648
649
650
651
652
653
654
655
656
657
658
659
660
661
662
663
664
665
666
667
668
669
670
671
672
673
674
675
676
677
678
679
680
681
682
683
684
685
686
687
688
689
690
691
692
693
694
695
696
697
698
699
700
701
702
703
704
705
706
707
708
709
710
711
712
713
714
715
716
717
718
719
720
721
722
723
724
725
726
727
728
729
730
731
732
733
734
735
736
737
738
739
740
741
742
743
744
745
746
747
748
749
750
751
752
753
754
755
756
757
758
759
760
761
762
763
764
765
766
767
768
769
770
771
772
773
774
775
776
777
778
779
780
781
782
783
784
785
786
787
788
789
790
791
792
793
794
795
796
797
798
799
800
801
802
803
804
805
806
807
808
809
810
811
812
813
814
815
816
817
818
819
820
821
822
823
824
825
826
827
828
829
830
831
832
833
834
835
836
837
838
839
840
841
842
843
844
845
846
847

TypeError: a bytes-like object is required, not 'NoneType'

In [ ]:
#extract shoton stat for home and away team from cross column

#EPL
home_shoton =[]
away_shoton =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['shoton'][i])
    home_shoton_count = 0
    away_shoton_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_shoton_count +=1
            else:
                away_shoton_count +=1
    home_shoton.append(home_shoton_count)
    away_shoton.append(away_shoton_count)
    
df_EPL.loc[:,"home_shoton"] = home_shoton
df_EPL.loc[:,"away_shoton"] = away_shoton

#LALIGA
home_shoton =[]
away_shoton =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['shoton'][i])
    home_shoton_count = 0
    away_shoton_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_shoton_count +=1
            else:
                away_shoton_count +=1
    home_shoton.append(home_shoton_count)
    away_shoton.append(away_shoton_count)
    
df_LaLiga.loc[:,"home_shoton"] = home_shoton
df_LaLiga.loc[:,"away_shoton"] = away_shoton


#extract shotoff stat for home and away team from cross column

#EPL
home_shotoff =[]
away_shotoff =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['shotoff'][i])
    home_shotoff_count = 0
    away_shotoff_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_shotoff_count +=1
            else:
                away_shotoff_count +=1
    home_shotoff.append(home_shotoff_count)
    away_shotoff.append(away_shotoff_count)
df_EPL.loc[:,"home_shotoff"] = home_shotoff
df_EPL.loc[:,"away_shotoff"] = away_shotoff

#LALIGA
home_shotoff =[]
away_shotoff =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['shotoff'][i])
    home_shotoff_count = 0
    away_shotoff_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_shotoff_count +=1
            else:
                away_shotoff_count +=1
    home_shotoff.append(home_shotoff_count)
    away_shotoff.append(away_shotoff_count)
df_LaLiga.loc[:,"home_shotoff"] = home_shotoff
df_LaLiga.loc[:,"away_shotoff"] = away_shotoff
    
    
    
#extract foulcommit stat for home and away team from cross column

#EPL
home_foulcommit =[]
away_foulcommit =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['foulcommit'][i])
    home_foulcommit_count = 0
    away_foulcommit_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_foulcommit_count +=1
            else:
                away_foulcommit_count +=1
    home_foulcommit.append(home_foulcommit_count)
    away_foulcommit.append(away_foulcommit_count)
df_EPL.loc[:,"home_foulcommit"] = home_foulcommit
df_EPL.loc[:,"away_foulcommit"] = away_foulcommit

#LALIGA
home_foulcommit =[]
away_foulcommit =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['foulcommit'][i])
    home_foulcommit_count = 0
    away_foulcommit_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_foulcommit_count +=1
            else:
                away_foulcommit_count +=1
    home_foulcommit.append(home_foulcommit_count)
    away_foulcommit.append(away_foulcommit_count)
df_LaLiga.loc[:,"home_foulcommit"] = home_foulcommit
df_LaLiga.loc[:,"away_foulcommit"] = away_foulcommit


#extract cross stat for home and away team from cross column

#EPL
home_cross =[]
away_cross =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['cross'][i])
    home_cross_count = 0
    away_cross_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_cross_count +=1
            else:
                away_cross_count +=1
    home_cross.append(home_cross_count)
    away_cross.append(away_cross_count)
df_EPL.loc[:,"home_cross"] = home_cross
df_EPL.loc[:,"away_cross"] = away_cross

#LALIGA
home_cross =[]
away_cross =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['cross'][i])
    home_cross_count = 0
    away_cross_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_cross_count +=1
            else:
                away_cross_count +=1
    home_cross.append(home_cross_count)
    away_cross.append(away_cross_count)
df_LaLiga.loc[:,"home_cross"] = home_cross
df_LaLiga.loc[:,"away_cross"] = away_cross



#extract corner stat for home and away team from corner column

#EPL
home_corner =[]
away_corner =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['corner'][i])
    home_corner_count = 0
    away_corner_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_corner_count +=1
            else:
                away_corner_count +=1
    home_corner.append(home_corner_count)
    away_corner.append(away_corner_count)
df_EPL.loc[:,"home_corner"] = home_corner
df_EPL.loc[:,"away_corner"] = away_corner
#LALIGA
home_corner =[]
away_corner =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['corner'][i])
    home_corner_count = 0
    away_corner_count = 0
    for child in root:
        if type(child.find('team')) != NoneType:
            if child.find('team').text == str(df_EPL['home_team_api_id'][i]):
                home_corner_count +=1
            else:
                away_corner_count +=1
    home_corner.append(home_corner_count)
    away_corner.append(away_corner_count)
df_LaLiga.loc[:,"home_corner"] = home_corner
df_LaLiga.loc[:,"away_corner"] = away_corner

# extract full game possession for home and away team from possession column
# few data rows do not have 90 minutes data but only 80+ mins, so we set the fulltime possession threshold to 80 mins up.
#EPL
home_possession =[]
away_possession =[]
NoneType = type(None)
for i in range(len(df_EPL)):
    root = ET.fromstring(df_EPL['possession'][i])
    for child in root:
        if type(child.find('elapsed')) != NoneType:
            if int(child.find('elapsed').text) > 80:
                if type(child.find('homepos')) != NoneType:
                    home_pos = child.find('homepos').text
                if type(child.find('awaypos')) != NoneType:
                    away_pos = child.find('awaypos').text
                
    home_possession.append(home_pos)
    away_possession.append(away_pos)
df_EPL.loc[:,"home_possession"] = home_possession
df_EPL.loc[:,"away_possession"] = away_possession

#LALIGA
home_possession =[]
away_possession =[]
NoneType = type(None)
for i in range(len(df_LaLiga)):
    root = ET.fromstring(df_LaLiga['possession'][i])
    for child in root:
        if type(child.find('elapsed')) != NoneType:
            if int(child.find('elapsed').text) > 80:
                if type(child.find('homepos')) != NoneType:
                    home_pos = child.find('homepos').text
                if type(child.find('awaypos')) != NoneType:
                    away_pos = child.find('awaypos').text
                
    home_possession.append(home_pos)
    away_possession.append(away_pos)
df_LaLiga.loc[:,"home_possession"] = home_possession
df_LaLiga.loc[:,"away_possession"] = away_possession

In [118]:
h = df_LaLiga.filter(like='home_team_api_id')
df_LaLiga[h.columns] = h.replace(m)
a = df_LaLiga.filter(like='away_team_api_id')
df_LaLiga[a.columns] = a.replace(m)

In [91]:
#df_EPL.sort_values(by=['away_r_card'], inplace=True, ascending=False)

In [119]:
pd.set_option('display.max_columns', None)

df_EPL_sort = df_EPL[df_EPL.columns.drop(list(matches.filter(regex='country_id|league_id|card|^goal$|^foulcommit$|^shoton$|^shotoff$|cross|corner|possession')))]
df_EPL_sort.sort_values(by=['date','home_team_api_id'], inplace=True, ascending=True)
df_EPL_sort

C:\Users\skylar_studio\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A,home_y_card,home_r_card,away_y_card,away_r_card
1,1730,2008/2009,1,2008-08-16 00:00:00,489043,Arsenal,West Bromwich Albion,1,0,1.20,6.50,15.00,0,0,0,0
7,1736,2008/2009,1,2008-08-16 00:00:00,489049,Bolton Wanderers,Stoke City,3,1,1.83,3.50,4.50,1,0,2,0
5,1734,2008/2009,1,2008-08-16 00:00:00,489047,Everton,Blackburn Rovers,2,3,2.00,3.30,4.00,2,0,2,0
8,1737,2008/2009,1,2008-08-16 00:00:00,489050,Hull City,Fulham,2,1,2.60,3.20,2.80,3,0,0,0
6,1735,2008/2009,1,2008-08-16 00:00:00,489048,Middlesbrough,Tottenham Hotspur,2,1,3.20,3.40,2.25,1,0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2976,4705,2015/2016,38,2016-05-15 00:00:00,1987603,Stoke City,West Ham United,2,1,3.50,3.60,2.15,3,0,1,0
2977,4706,2015/2016,38,2016-05-15 00:00:00,1987604,Swansea City,Manchester City,1,1,6.00,4.75,1.53,1,0,3,0
2978,4707,2015/2016,38,2016-05-15 00:00:00,1987605,Watford,Sunderland,2,2,2.05,3.75,3.70,1,0,0,0
2979,4708,2015/2016,38,2016-05-15 00:00:00,1987606,West Bromwich Albion,Liverpool,1,1,2.40,3.60,3.00,3,0,1,0
2973,4702,2015/2016,38,2016-05-17 00:00:00,1987600,Manchester United,Bournemouth,3,1,1.67,4.20,5.25,1,0,0,0

In [116]:
df_LaLiga.home_team_api_id.unique()

array(['Valencia CF', 'CA Osasuna', 'RC Deportivo de La Coruña',
       'CD Numancia', 'Racing Santander', 'Real Sporting de Gijón',
       'Real Betis Balompié', 'RCD Espanyol', 'Athletic Club de Bilbao',
       'Atlético Madrid', 'Sevilla FC', 'Villarreal CF', 'Real Madrid CF',
       'FC Barcelona', 'Getafe CF', 'RCD Mallorca', 'UD Almería',
       'Málaga CF', 'Real Valladolid', 'RC Recreativo', 'Real Zaragoza',
       'CD Tenerife', 'Xerez Club Deportivo', 'Hércules Club de Fútbol',
       'Levante UD', 'Real Sociedad', 'Rayo Vallecano', 'Granada CF',
       'RC Celta de Vigo', 'Elche CF', 'SD Eibar', 'Córdoba CF',
       'UD Las Palmas'], dtype=object)

In [117]:
df_LaLiga_stat.HomeTeam.unique()

array(['Espanol', 'Valencia', 'Ath Bilbao', 'Ath Madrid', 'Betis',
       'La Coruna', 'Numancia', 'Osasuna', 'Santander', 'Sp Gijon',
       'Barcelona', 'Valladolid', 'Almeria', 'Getafe', 'Malaga',
       'Mallorca', 'Real Madrid', 'Recreativo', 'Sevilla', 'Villarreal',
       'Zaragoza', 'Tenerife', 'Xerez', 'Hercules', 'Levante', 'Sociedad',
       'Granada', 'Vallecano', 'Celta', 'Elche', 'Eibar', 'Cordoba',
       'Las Palmas'], dtype=object)

In [137]:
pd.set_option('display.max_columns', None)

df_LaLiga_sort = df_LaLiga[df_LaLiga.columns.drop(list(matches.filter(regex='country_id|league_id|card|^goal$|^foulcommit$|^shoton$|^shotoff$|cross|corner|possession')))]
df_LaLiga_sort.sort_values(by=['date','home_team_api_id'], inplace=True, ascending=True)
df_LaLiga_sort

C:\Users\skylar_studio\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

,id,season,stage,date,match_api_id,home_team_api_id,away_team_api_id,home_team_goal,away_team_goal,B365H,B365D,B365A
7,21525,2008/2009,1,2008-08-30 00:00:00,530090,RCD Espanyol,Real Valladolid,1,0,2.00,3.30,3.80
0,21518,2008/2009,1,2008-08-30 00:00:00,530023,Valencia CF,RCD Mallorca,3,0,1.70,3.60,5.25
8,21526,2008/2009,1,2008-08-31 00:00:00,530091,Athletic Club de Bilbao,UD Almería,1,3,2.00,3.30,3.80
9,21527,2008/2009,1,2008-08-31 00:00:00,530092,Atlético Madrid,Málaga CF,4,0,1.44,4.20,7.50
1,21519,2008/2009,1,2008-08-31 00:00:00,530084,CA Osasuna,Villarreal CF,1,1,2.80,3.30,2.50
...,...,...,...,...,...,...,...,...,...,...,...,...
2977,24495,2015/2016,38,2016-05-15 00:00:00,2030535,Málaga CF,UD Las Palmas,4,1,1.80,3.75,4.50
2974,24492,2015/2016,38,2016-05-15 00:00:00,2030532,RCD Espanyol,SD Eibar,4,2,2.00,3.60,3.70
2979,24497,2015/2016,38,2016-05-15 00:00:00,2030537,Rayo Vallecano,Levante UD,3,1,1.33,5.25,9.00
2973,24491,2015/2016,38,2016-05-15 00:00:00,2030531,Real Betis Balompié,Getafe CF,2,1,5.00,3.80,1.70
2972,24490,2015/2016,38,2016-05-15 00:00:00,2030530,Real Sporting de Gijón,Villarreal CF,2,0,1.44,4.50,7.50

In [167]:
df_EPL.to_csv(path + "EPL.csv")
df_LaLiga.to_csv(path + "LaLiga.csv")

In [168]:
df_epl_stat = pd.read_csv('epl_stats.csv')
df_epl_stat

,Unnamed: 0,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,0,8/11/2007,Aston Villa,Liverpool,1,2,A,0,0,0,0,0,0
1,1,8/11/2007,Bolton,Newcastle,1,3,A,0,0,0,0,0,0
2,2,8/11/2007,Derby,Portsmouth,2,2,D,0,0,0,0,0,0
3,3,8/11/2007,Everton,Wigan,2,1,H,0,0,0,0,0,0
4,4,8/11/2007,Middlesbrough,Blackburn,1,2,A,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,375,5/15/2016,Stoke,West Ham,2,1,H,39,64,54,49,48,62
3416,376,5/15/2016,Swansea,Man City,1,1,D,41,70,51,40,46,65
3417,377,5/15/2016,Watford,Sunderland,2,2,D,38,46,48,60,44,38
3418,378,5/15/2016,West Brom,Liverpool,1,1,D,33,62,47,49,42,59
3419,379,5/17/2016,Man United,Bournemouth,3,1,H,46,44,34,64,63,42

In [169]:
len(df_epl_stat)

3420

In [185]:
df_LaLiga_stat = pd.read_csv('la_liga_stats.csv')
dict1 = ['Espanol', 'Valencia', 'Ath Bilbao', 'Ath Madrid', 'Betis',
       'La Coruna', 'Numancia', 'Osasuna', 'Santander', 'Sp Gijon',
       'Barcelona', 'Valladolid', 'Almeria', 'Getafe', 'Malaga',
       'Mallorca', 'Real Madrid', 'Recreativo', 'Sevilla', 'Villarreal',
       'Zaragoza', 'Tenerife', 'Xerez', 'Hercules', 'Levante', 'Sociedad',
       'Granada', 'Vallecano', 'Celta', 'Elche', 'Eibar', 'Cordoba',
       'Las Palmas']

dict2 = ['RCD Espanyol','Valencia CF','Athletic Club de Bilbao','Atlético Madrid','Real Betis Balompié',
        'RC Deportivo de La Coruña','CD Numancia','CA Osasuna','Racing Santander', 'Real Sporting de Gijón',
         'FC Barcelona','Real Valladolid','UD Almería','Getafe CF','Málaga CF',
         'RCD Mallorca','Real Madrid CF', 'RC Recreativo', 'Sevilla FC','Villarreal CF',
         'Real Zaragoza', 'CD Tenerife', 'Xerez Club Deportivo', 'Hércules Club de Fútbol', 'Levante UD', 'Real Sociedad',
         'Granada CF', 'Rayo Vallecano', 'RC Celta de Vigo', 'Elche CF', 'SD Eibar', 'Córdoba CF',
         'UD Las Palmas']


dict3 = ['Valencia CF', 'CA Osasuna', 'RC Deportivo de La Coruña',
       'CD Numancia', 'Racing Santander', 'Real Sporting de Gijón',
       'Real Betis Balompié', 'RCD Espanyol', 'Athletic Club de Bilbao',
       'Atlético Madrid', 'Sevilla FC', 'Villarreal CF', 'Real Madrid CF',
       'FC Barcelona', 'Getafe CF', 'RCD Mallorca', 'UD Almería',
       'Málaga CF', 'Real Valladolid', 'RC Recreativo', 'Real Zaragoza',
       'CD Tenerife', 'Xerez Club Deportivo', 'Hércules Club de Fútbol',
       'Levante UD', 'Real Sociedad', 'Rayo Vallecano', 'Granada CF',
       'RC Celta de Vigo', 'Elche CF', 'SD Eibar', 'Córdoba CF',
       'UD Las Palmas']
m = dict(zip(dict1, dict2))
h = df_LaLiga_stat.filter(like='HomeTeam')
df_LaLiga_stat[h.columns] = h.replace(m)
a = df_LaLiga_stat.filter(like='AwayTeam')
df_LaLiga_stat[a.columns] = a.replace(m)
df_LaLiga_stat

,Unnamed: 0,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
0,0,8/25/2007,Real Madrid CF,Atlético Madrid,2,1,H,0,0,0,0,0,0
1,1,8/25/2007,Sevilla FC,Getafe CF,4,1,H,0,0,0,0,0,0
2,2,8/26/2007,Athletic Club de Bilbao,CA Osasuna,0,0,D,0,0,0,0,0,0
3,3,8/26/2007,RCD Espanyol,Real Valladolid,0,1,A,0,0,0,0,0,0
4,4,8/26/2007,RC Deportivo de La Coruña,UD Almería,0,3,A,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
3415,375,5/15/2016,Real Betis Balompié,Getafe CF,2,1,H,32,36,51,65,42,36
3416,376,5/15/2016,RCD Espanyol,SD Eibar,4,2,H,36,47,72,57,40,43
3417,377,5/15/2016,Málaga CF,UD Las Palmas,4,1,H,34,44,34,49,45,44
3418,378,5/15/2016,Real Sporting de Gijón,Villarreal CF,2,0,H,38,44,62,33,36,64
3419,379,5/15/2016,Rayo Vallecano,Levante UD,3,1,H,49,36,72,67,35,32

In [186]:
len(df_epl_stat)

3040

In [187]:
len(df_LaLiga_stat)

3420

In [210]:
df_epl_stat = df_epl_stat.iloc[-3040:]
df_epl_stat.tail(10)

,Unnamed: 0,Date,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTGS,ATGS,HTGC,ATGC,HTP,ATP
3410,370,5/15/2016,Arsenal,Aston Villa,4,0,H,61,27,36,72,68,17
3411,371,5/15/2016,Chelsea,Leicester,1,1,D,58,67,52,35,49,80
3412,372,5/15/2016,Everton,Norwich,3,0,H,56,39,55,64,44,34
3413,373,5/15/2016,Newcastle,Tottenham,5,1,H,39,68,64,30,34,70
3414,374,5/15/2016,Southampton,Crystal Palace,4,1,H,55,38,40,47,60,42
3415,375,5/15/2016,Stoke,West Ham,2,1,H,39,64,54,49,48,62
3416,376,5/15/2016,Swansea,Man City,1,1,D,41,70,51,40,46,65
3417,377,5/15/2016,Watford,Sunderland,2,2,D,38,46,48,60,44,38
3418,378,5/15/2016,West Brom,Liverpool,1,1,D,33,62,47,49,42,59
3419,379,5/17/2016,Man United,Bournemouth,3,1,H,46,44,34,64,63,42

In [211]:
df_LaLiga_stat = df_LaLiga_stat.iloc[-3040:]
df_LaLiga_stat['Date'] = pd.to_datetime(df_LaLiga_stat['Date'], format='%m/%d/%Y')
df_LaLiga_stat.sort_values(by=['Date','HomeTeam'], inplace=True, ascending=True)

In [212]:
df_EPL_sort.loc[:,"HTP"]  = df_epl_stat_['HTP'].values.tolist()
df_EPL_sort.loc[:,"ATP"]  = df_epl_stat_['ATP'].values.tolist()
df_EPL_sort.loc[:,"Result"]  = df_epl_stat_['FTR'].values.tolist()

In [213]:
df_EPL_sort.to_csv(path + "EPL_sort.csv")

In [214]:
df_LaLiga_sort.loc[:,"HTP"]  = df_LaLiga_stat['HTP'].values.tolist()
df_LaLiga_sort.loc[:,"ATP"]  = df_LaLiga_stat['ATP'].values.tolist()
df_LaLiga_sort.loc[:,"Result"]  = df_LaLiga_stat['FTR'].values.tolist()

In [215]:
df_EPL_sort.to_csv(path + "EPL_sort.csv")

In [216]:
df_LaLiga_sort.to_csv(path + "LaLiga_sort.csv")